# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Which is equivalent to
format = """
$username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$custom\
$sudo\
$cmd_duration\
$jobs\
$container\
$shell\
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

[kubernetes]
disabled = false

[directory]
truncate_to_repo = false

